language: csharp
mono: none
dotnet: 2.1
os: linux
sudo: false
dist: trusty
addons:
  apt:
    sources:
    packages:
env:
  matrix:
    - target="src/Microsoft.Azure.IIoT.Proxy.Api/src" framework="netstandard2.0"
    - target="src/Microsoft.Azure.IIoT.Proxy.Api/cli" framework="netcoreapp2.1"
    - target="src/Microsoft.Azure.IIoT.OpcUa.Proxy/src" framework="netstandard2.0"
    - target="src/Microsoft.Azure.IIoT.OpcUa.Proxy/cli" framework="netcoreapp2.1"
    - target="src/Microsoft.Azure.IIoT.Net.Netcat/src" framework="netcoreapp2.1"
    - target="src/Microsoft.Azure.IIoT.Http.Relay/src" framework="netcoreapp2.1"
install:
script: 
  - dotnet restore
  - cd "$target"
  - dotnet build -f $framework -c Debug
  - dotnet build -f $framework -c Release
