language: c
sudo: required
dist: trusty
env:
  matrix:
    - target="src/Microsoft.Azure.Devices.Proxy" framework="netstandard2.0"
    - target="samples/opc-ua/src/Microsoft.Azure.Devices.Proxy.Opc.Ua" framework="netstandard2.0"
    - target="samples/simple/tcp" framework="netcoreapp2.1"
    - target="samples/netcat" framework="netcoreapp2.1"
install:
  - wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get install apt-transport-https -y
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.1 -y
script: 
  - dotnet restore
  - cd "$target"
  - dotnet build -f $framework -c Debug
  - dotnet build -f $framework -c Release
